#!/bin/bash

shopt -s nullglob

# HTTP Basic-Auth credentials
HTTP_USER=phish
HTTP_PASSWORD=phishy

CATEGORIES=(crime apt)

for category in ${CATEGORIES[*]}; do
	echo ">>> Updating $category ..."

	mkdir -p $category/
	pushd $category/ >/dev/null

	wget -q -nc -A "*.zip" --http-user=$HTTP_USER --http-password=$HTTP_PASSWORD https://trailofphish.com/emails/$category/ $category/

	echo ">>> Extracting new archives ..."

	for archive in $category/*.zip; do
		unzip -n -P infected $archive -d $category/
	done

	popd >/dev/null
done
