#!/bin/bash

UPLOAD_HOST=trailofphish.com
UPLOAD_USER=phish

function usage() {
	echo "usage: upload FILE CATEGORY"
	exit -1
}

[[ ! $# -eq 2 ]] && usage

FILE=$1
CATEGORY=$2

if [[ ! -f $FILE ]]; then
	echo "!!! Could not find file $FILE"
	exit -1
fi

echo ">>> Uploading $FILE into $CATEGORY"

scp $FILE $UPLOAD_USER@$UPLOAD_HOST:/home/$UPLOAD_USER/emails/$CATEGORY/

if [[ $? -eq 0 ]]; then
	echo ">>> Uploaded $FILE!"
else
	echo "!!! Unable to upload $FILE to $CATEGORY!"
	exit -1
fi
